# Generated by Django 2.2.13 on 2021-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_store_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
