# Generated by Django 2.2.13 on 2021-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('employee_id', models.AutoField(default=10000, max_length=6, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
