# Generated by Django 2.2.13 on 2021-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
