# Generated by Django 2.2.13 on 2021-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_auth', '0002_auto_20210217_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='employee_id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
