# Generated by Django 2.2.13 on 2021-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('genere', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
